
title: CryptoHodl24 - Новости из мира криптовалют
name: CryptoHodl24
description: Новости из мира криптовалют, технологий и другое.

themecolor: '#202225'
imagehome: img/cryptohodl24.jpg
url: 'http://cryptohodl24.ru'
baseurl: '/'

plugins: [jekyll-paginate-v2]
category_dir: blog
pagination:
  enable: true
  per_page: 9
  title: ':title - Страница :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
   before: 2
   after: 2
  
exclude: ['node-modules', 'gulpfile.js', 'package.json', 'package-lock.json', 'js/common.js', 'npm-debug.log', '**/Thumbs.db', 'libs', 'sass', '**/*.DS_Store']

soc:
    <li><a href="#"><i class="fa fa-vk"></i></a></li>
    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
    <li><a href="#"><i class="fa fa-odnoklassniki"></i></a></li>
    <li><a href="#"><i class="fa fa-instagram"></i></a></li>
    <li><a href="#"><i class="fa fa-rss"></i></a></li>

copyright: Копирование контенте и размещение на других сайтах запрещено.
   

 